# Install core
COPY install/core.sh /install/core.sh
RUN bash /install/core.sh

# Install Conda
ENV PATH=/opt/conda/bin:${PATH}
COPY install/conda.sh /install/conda.sh
ADD conda/ /install/conda/
RUN bash /install/conda.sh

# Install auditwheel
COPY install/auditwheel.sh /install/auditwheel.sh
RUN bash /install/auditwheel.sh
ENV AUDITWHEEL_PLAT=manylinux_2_28_x86_64
